export const CANVAS_WIDTH = Math.min(500, window.innerWidth)
export const CANVAS_HEIGHT = window.innerHeight
export const DELTA_TIME = 7
export const BALL_SIZE = 50
export const COLOR = [0xf07878, 0x9ad2f5, 0xf5d095, 0xacfabd]
export const FLOOR_SPEED = -3
export const JUMP_SPEED = -10
export const FALL_SPEED = 10
export const TIME_TO_CHANGE_COLOR = 5
export const TIME_TO_SPAWN_OBJECT = 60
export const FLOOR_DOWN_SPEED = 2
